apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: za7p62gtg-nodejs
  janus-idp.io/tekton: za7p62gtg-nodejs
  backstage.io/kubernetes-id: za7p62gtg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: za7p62gtg-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
